#version 430 core
layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer LayerKeys {
    float keys[]; // 每元素 4 个 float: layerID, orderInLayer, sortedIndex, instanceIndex
};

layout(std430, binding = 1) buffer GlobalKeys {
    float global[]; // 每元素 2 个 float: distance, instanceIndex
};

uniform int layerCount;

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= layerCount) return;

    float sortedIdx = keys[id*4+2];
    float instIdx   = keys[id*4+3];
    // 只更新实例索引，距离字段保持不变
    global[uint(sortedIdx)*2+1] = instIdx;
}